version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:1.0
    ports:
      - ${PORTUI}:${PORTUI}/tcp
    networks:
      front_net:
  post:
    image: ${USER_NAME}/post:1.0
    networks:
      back_net:
      front_net:
  comment:
    image: ${USER_NAME}/comment:1.0
    networks:
      back_net:
      front_net:

volumes:
  post_db:
networks:
  back_net:
  front_net:
