---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
 name: post
 labels:
  app: reddit
  component: post
spec:
 replicas: 1
 selector:
  matchLabels:
   app: reddit
   component: post
 template:
  metadata:
   name: post
   labels:
    app: reddit
    component: post
  spec:
   containers:
   - image: kuvshinov/post:1.0
     name: post
     env:
      - name: POST_DATABASE_HOST
        value: post-db
