version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:${VOLUMEDB}
    networks:
       back_net:
         aliases:
              - post_db
              - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UIVERSION}
    ports: 
      - ${PORTUI}:${PORTUI}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POSTVERSION}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENTVERSION}
    networks:
      - back_net
      - front_net
volumes:
  post_db:

networks:
  back_net:
  front_net:
